DATA:
  set: movi_b
  max_objs: 10
  fps: 12
  fpv: 24
  height: 256
  width: 256


TRAIN:
  self_sup: True
  forecast: 3

  STAGE_1:
    include: True
    num_epoch: 100

  STAGE_2:
    include: True
    num_epoch: 100
    spp: 4
    weight_mse: 1.0

  OPTIM:
    optim: adam
    lr: 0.001
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0.0

  GPU:
    model: NVIDIA GeForce RTX A6000


TEST:
  OBJ_MOD:
    include: True

  VID_PRED:
    include: True
    spp: 16

  GPU:
    model: NVIDIA GeForce GTX 1060


MODEL:
  window: 3
  
  INPUT:
    video: True
    depth: True
    opt_flow: True
    mask: True

  ENCODE:
    TEMP:
      arch: resnet_18
      dropout: 0.1
      activation: relu
      batch_norm: True
      embed_size: 512

    PRIOR:
      cam_pos: True
      cam_ori: True
      obj_class: True
      num_obj_class: 11
      arch: mlp
      num_layers: 1
      hidden_size: 2048
      dropout: 0.1
      activation: relu
      batch_norm: True
      embed_size: 512

    INTER:
      include: True
      arch: transformer_encoder
      num_layers: 1
      num_heads: 8
      dropout: 0.1
      hidden_size: 2048
      embed_size: 512

  DECODE:
    BASE:
      arch: mlp
      num_layers: 1
      hidden_size: 2048
      dropout: 0.1
      activation: relu
      batch_norm: True
      category_est: gumbel_softmax

    PARAM:
      SIZE:
        include: True
        continuous: True

      POS:
        include: True
        continuous: True

      ORI:
        include: True
        continuous: True

      LIN_VEL:
        include: True
        continuous: True

      ANG_VEL:
        include: True
        continuous: True

      MATERIAL:
        include: True
        continuous: False
        num_class: 2

      COLOR:
        include: True
        continuous: True
